on: [push]

name: Build

jobs:
# Linux {{{

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Build
        run: >
          cargo build --workspace --release &&
          strip -s target/release/bibe &&
          mv target/release/bibe target/release/bibe_amd64

      - name: Lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Release Bibe
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/bibe')
        with:
          files: |
            target/release/bibe_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# }}}
# Windows {{{

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --release

      - name: Release Bibe
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/bibe')
        with:
          files: target/release/bibe.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# }}}
# MacOS {{{

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin

      - name: Build
        run: >
          cargo build --workspace --release &&
          strip -SxD target/release/bibe &&
          mv target/release/bibe target/release/bibe_darwin

      - name: Release Bibe
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/bibe')
        with:
          files: |
            target/release/bibe_darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# }}}
